// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorTile19 = new Entity("floor tile")
engine.addEntity(floorTile19)
const floorTile19transform = new Transform({
  position: new Vector3(24, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorTile19.addComponentOrReplace(floorTile19transform)
const floorTile19GLTFShape = new GLTFShape("models/floor_tile/floor_tile.glb")
floorTile19GLTFShape.withCollisions = true
floorTile19GLTFShape.isPointerBlocker = true
floorTile19GLTFShape.visible = true
floorTile19.addComponentOrReplace(floorTile19GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorTile20 = new Entity("floor tile")
engine.addEntity(floorTile20)
const floorTile20transform = new Transform({
  position: new Vector3(8, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorTile20.addComponentOrReplace(floorTile20transform)
floorTile20.addComponentOrReplace(floorTile19GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorTile22 = new Entity("floor tile")
engine.addEntity(floorTile22)
const floorTile22transform = new Transform({
  position: new Vector3(8, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorTile22.addComponentOrReplace(floorTile22transform)
floorTile22.addComponentOrReplace(floorTile19GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const floorTile23 = new Entity("floor tile")
engine.addEntity(floorTile23)
const floorTile23transform = new Transform({
  position: new Vector3(24, 0, 24),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
floorTile23.addComponentOrReplace(floorTile23transform)
floorTile23.addComponentOrReplace(floorTile19GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple24 = new Entity("platform purple")
engine.addEntity(platformPurple24)
const platformPurple24transform = new Transform({
  position: new Vector3(23.5, 7.5, 18.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple24.addComponentOrReplace(platformPurple24transform)
const platformPurple24GLTFShape = new GLTFShape("models/platform_purple1/platform_purple1.glb")
platformPurple24GLTFShape.withCollisions = true
platformPurple24GLTFShape.isPointerBlocker = true
platformPurple24GLTFShape.visible = true
platformPurple24.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple25 = new Entity("platform purple")
engine.addEntity(platformPurple25)
const platformPurple25transform = new Transform({
  position: new Vector3(13.5, 2, 18),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple25.addComponentOrReplace(platformPurple25transform)
platformPurple25.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple26 = new Entity("platform purple")
engine.addEntity(platformPurple26)
const platformPurple26transform = new Transform({
  position: new Vector3(9, 0.5, 13.59),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple26.addComponentOrReplace(platformPurple26transform)
platformPurple26.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple27 = new Entity("platform purple")
engine.addEntity(platformPurple27)
const platformPurple27transform = new Transform({
  position: new Vector3(22.5, 4.5, 26.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple27.addComponentOrReplace(platformPurple27transform)
platformPurple27.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple29 = new Entity("platform purple")
engine.addEntity(platformPurple29)
const platformPurple29transform = new Transform({
  position: new Vector3(18, 3.5, 22.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple29.addComponentOrReplace(platformPurple29transform)
platformPurple29.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple31 = new Entity("platform purple")
engine.addEntity(platformPurple31)
const platformPurple31transform = new Transform({
  position: new Vector3(27, 6, 23),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple31.addComponentOrReplace(platformPurple31transform)
platformPurple31.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformBlue233 = new Entity("platform blue 2")
engine.addEntity(platformBlue233)
const platformBlue233transform = new Transform({
  position: new Vector3(22, 13, 9),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformBlue233.addComponentOrReplace(platformBlue233transform)
const platformBlue233GLTFShape = new GLTFShape("models/platform_blue/platform_blue.glb")
platformBlue233GLTFShape.withCollisions = true
platformBlue233GLTFShape.isPointerBlocker = true
platformBlue233GLTFShape.visible = true
platformBlue233.addComponentOrReplace(platformBlue233GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformBlue134 = new Entity("platform blue 1")
engine.addEntity(platformBlue134)
const platformBlue134transform = new Transform({
  position: new Vector3(18.5, 9, 13.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformBlue134.addComponentOrReplace(platformBlue134transform)
platformBlue134.addComponentOrReplace(platformBlue233GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformBlue335 = new Entity("platform blue 3")
engine.addEntity(platformBlue335)
const platformBlue335transform = new Transform({
  position: new Vector3(3.5, 21.5, 22.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformBlue335.addComponentOrReplace(platformBlue335transform)
platformBlue335.addComponentOrReplace(platformBlue233GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformBlue436 = new Entity("platform blue 4")
engine.addEntity(platformBlue436)
const platformBlue436transform = new Transform({
  position: new Vector3(13.5, 28.5, 3.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformBlue436.addComponentOrReplace(platformBlue436transform)
platformBlue436.addComponentOrReplace(platformBlue233GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformBlue537 = new Entity("platform blue 5")
engine.addEntity(platformBlue537)
const platformBlue537transform = new Transform({
  position: new Vector3(23, 33, 22.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformBlue537.addComponentOrReplace(platformBlue537transform)
platformBlue537.addComponentOrReplace(platformBlue233GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple38 = new Entity("platform purple")
engine.addEntity(platformPurple38)
const platformPurple38transform = new Transform({
  position: new Vector3(13, 10.5, 9.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple38.addComponentOrReplace(platformPurple38transform)
platformPurple38.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple39 = new Entity("platform purple")
engine.addEntity(platformPurple39)
const platformPurple39transform = new Transform({
  position: new Vector3(17, 11.5, 5.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple39.addComponentOrReplace(platformPurple39transform)
platformPurple39.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple40 = new Entity("platform purple")
engine.addEntity(platformPurple40)
const platformPurple40transform = new Transform({
  position: new Vector3(17.5, 14.5, 13.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple40.addComponentOrReplace(platformPurple40transform)
platformPurple40.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple41 = new Entity("platform purple")
engine.addEntity(platformPurple41)
const platformPurple41transform = new Transform({
  position: new Vector3(22.5, 16, 17.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple41.addComponentOrReplace(platformPurple41transform)
platformPurple41.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple42 = new Entity("platform purple")
engine.addEntity(platformPurple42)
const platformPurple42transform = new Transform({
  position: new Vector3(18, 17.5, 22),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple42.addComponentOrReplace(platformPurple42transform)
platformPurple42.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple43 = new Entity("platform purple")
engine.addEntity(platformPurple43)
const platformPurple43transform = new Transform({
  position: new Vector3(13.5, 19, 26.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple43.addComponentOrReplace(platformPurple43transform)
platformPurple43.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple44 = new Entity("platform purple")
engine.addEntity(platformPurple44)
const platformPurple44transform = new Transform({
  position: new Vector3(8, 20, 26),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple44.addComponentOrReplace(platformPurple44transform)
platformPurple44.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple46 = new Entity("platform purple")
engine.addEntity(platformPurple46)
const platformPurple46transform = new Transform({
  position: new Vector3(3.5, 22.5, 16.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple46.addComponentOrReplace(platformPurple46transform)
platformPurple46.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple47 = new Entity("platform purple")
engine.addEntity(platformPurple47)
const platformPurple47transform = new Transform({
  position: new Vector3(4.5, 25.5, 5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple47.addComponentOrReplace(platformPurple47transform)
platformPurple47.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple48 = new Entity("platform purple")
engine.addEntity(platformPurple48)
const platformPurple48transform = new Transform({
  position: new Vector3(8, 27, 3.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple48.addComponentOrReplace(platformPurple48transform)
platformPurple48.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple49 = new Entity("platform purple")
engine.addEntity(platformPurple49)
const platformPurple49transform = new Transform({
  position: new Vector3(18.5, 29.5, 7.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple49.addComponentOrReplace(platformPurple49transform)
platformPurple49.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple50 = new Entity("platform purple")
engine.addEntity(platformPurple50)
const platformPurple50transform = new Transform({
  position: new Vector3(24, 31, 12.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple50.addComponentOrReplace(platformPurple50transform)
platformPurple50.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple51 = new Entity("platform purple")
engine.addEntity(platformPurple51)
const platformPurple51transform = new Transform({
  position: new Vector3(28, 32, 17.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple51.addComponentOrReplace(platformPurple51transform)
platformPurple51.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple52 = new Entity("platform purple")
engine.addEntity(platformPurple52)
const platformPurple52transform = new Transform({
  position: new Vector3(4, 24, 10.5),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple52.addComponentOrReplace(platformPurple52transform)
platformPurple52.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformPurple53 = new Entity("platform purple")
engine.addEntity(platformPurple53)
const platformPurple53transform = new Transform({
  position: new Vector3(18.5, 34, 18),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformPurple53.addComponentOrReplace(platformPurple53transform)
platformPurple53.addComponentOrReplace(platformPurple24GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const tower55 = new Entity("tower")
engine.addEntity(tower55)
const tower55transform = new Transform({
  position: new Vector3(16, 0, 16),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
tower55.addComponentOrReplace(tower55transform)
const tower55GLTFShape = new GLTFShape("models/tower/tower.glb")
tower55GLTFShape.withCollisions = true
tower55GLTFShape.isPointerBlocker = true
tower55GLTFShape.visible = true
tower55.addComponentOrReplace(tower55GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformGreen57 = new Entity("platform green")
engine.addEntity(platformGreen57)
const platformGreen57transform = new Transform({
  position: new Vector3(18.5, 35.5, 12),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformGreen57.addComponentOrReplace(platformGreen57transform)
const platformGreen57GLTFShape = new GLTFShape("models/platform_green/platform_green.glb")
platformGreen57GLTFShape.withCollisions = true
platformGreen57GLTFShape.isPointerBlocker = true
platformGreen57GLTFShape.visible = true
platformGreen57.addComponentOrReplace(platformGreen57GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const trebleClef58 = new Entity("treble clef")
engine.addEntity(trebleClef58)
const trebleClef58transform = new Transform({
  position: new Vector3(18.5, 36.25, 12),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
trebleClef58.addComponentOrReplace(trebleClef58transform)
const trebleClef58GLTFShape = new GLTFShape("models/treble_clef/treble_clef.glb")
trebleClef58GLTFShape.withCollisions = true
trebleClef58GLTFShape.isPointerBlocker = true
trebleClef58GLTFShape.visible = true
trebleClef58.addComponentOrReplace(trebleClef58GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const platformYellow60 = new Entity("platform yellow")
engine.addEntity(platformYellow60)
const platformYellow60transform = new Transform({
  position: new Vector3(9, 0, 8),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
platformYellow60.addComponentOrReplace(platformYellow60transform)
const platformYellow60GLTFShape = new GLTFShape("models/platform_yellow/platform_yellow.glb")
platformYellow60GLTFShape.withCollisions = true
platformYellow60GLTFShape.isPointerBlocker = true
platformYellow60GLTFShape.visible = true
platformYellow60.addComponentOrReplace(platformYellow60GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const trebleClef161 = new Entity("treble clef 1")
engine.addEntity(trebleClef161)
const trebleClef161transform = new Transform({
  position: new Vector3(9.25, 0.75, 7.25),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(1, 1, 1)
})
trebleClef161.addComponentOrReplace(trebleClef161transform)
trebleClef161.addComponentOrReplace(trebleClef58GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  platformBlue2:{
    entity: platformBlue233,
    transform: platformBlue233transform,
    GLTFShape: platformBlue233GLTFShape,
  },
  platformBlue1:{
    entity: platformBlue134,
    transform: platformBlue134transform,
    GLTFShape: platformBlue233GLTFShape,
  },
  platformBlue3:{
    entity: platformBlue335,
    transform: platformBlue335transform,
    GLTFShape: platformBlue233GLTFShape,
  },
  platformBlue4:{
    entity: platformBlue436,
    transform: platformBlue436transform,
    GLTFShape: platformBlue233GLTFShape,
  },
  platformBlue5:{
    entity: platformBlue537,
    transform: platformBlue537transform,
    GLTFShape: platformBlue233GLTFShape,
  },
  trebleClef:{
    entity: trebleClef58,
    transform: trebleClef58transform,
    GLTFShape: trebleClef58GLTFShape,
  },
  trebleClef1:{
    entity: trebleClef161,
    transform: trebleClef161transform,
    GLTFShape: trebleClef58GLTFShape,
  },
}

